easylife/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from . import forms

urlpatterns = [
    path('', include('landing.urls')),
    path('', include('roommates.urls')),
    path('', include('marketplace.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', RegistrationView.as_view(form_class=forms.RegistrationFormStevensEmail), name='registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = "landing"
urlpatterns = [
    path('', views.index, name='index'),
]

marketplace/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views as market_views

app_name = "marketplace"
urlpatterns = [
    path('market/', market_views.IndexView.as_view(), name='market_home'),
    path('market/<int:pk>/', market_views.DetailView.as_view(), name="detail"),
    path('market/create_post/', login_required(market_views.PostingCreateView.as_view()), name="make_post"),
    path('market/edit/<int:pk>', market_views.PostingUpdateView.as_view(), name="edit_post"),
    path('market/delete/<int:pk>', market_views.PostingDeleteView.as_view(), name="delete_post"),
    path('market/send_message/<int:posting_id>', login_required(market_views.send_message), name="send_message"),
    path('market/send_message/confirm/', market_views.send_message_confirm, name="send_message_confirm"),
]

roommates/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = "roommates"
urlpatterns = [
    path('rooms/', views.IndexView.as_view(), name='index'),
    path('rooms/<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('rooms/create_post/', login_required(views.PostingCreateView.as_view()), name="make_post"),
    path('rooms/edit/<int:pk>', views.PostingUpdateView.as_view(), name="edit_post"),
    path('rooms/delete/<int:pk>', views.PostingDeleteView.as_view(), name="delete_post"),
    path('rooms/send_message/<int:posting_id>', login_required(views.send_message), name="send_message"),
    path('rooms/send_message/confirm/', views.send_message_confirm, name="send_message_confirm"),
]

marketplace/models.py
import os.path

from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.db import models
from django.template.defaultfilters import slugify
from io import BytesIO
from PIL import Image

THUMB_SIZE = (200, 200)

class Posting(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="market_user")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/{self.id}/"


def get_image_filename(instance, filename):
    title = instance.posting.title
    slug = slugify(title)
    return "posting_images/%s-%s" % (slug, filename)

def get_thumbnail_filename(instance, filename):
    title = instance.posting.title
    slug = slugify(title)
    return "posting_thumbnails/%s-%s" % (slug, filename)

class Photo(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    alt_text = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name="Image", blank=True)
    thumbnail = models.ImageField(upload_to=get_thumbnail_filename,
                             verbose_name="Thumbnail", blank=True)

    def save(self, *args, **kwargs):
        if not self.make_thumbnail():
            # set to default thumbnail
            raise Exception("Could not create thumbnail - is the file type valid?")

        super(Photo, self).save(*args, **kwargs)

    def make_thumbnail(self):
        image = Image.open(self.image)
        image.thumbnail(THUMB_SIZE, Image.ANTIALIAS)

        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        thumb_extension = thumb_extension.lower()

        thumb_filename = thumb_name + '_thumb' + thumb_extension

        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False # Unrecognized file type
    
        temp_thumb = BytesIO()
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)

        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()

        return True

    def __str__(self):
        return self.alt_text

marketplace/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Photo, Posting


class MessageForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea,label="Message to poster")


class PostingForm(forms.ModelForm):
    class Meta:
        model = Posting
        fields = ('title', 'price', 'description',)
        labels = {
            'title': _('Posting Title'),
            'price': _('Price (dollars)'),
        }

class PhotoForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Photo
        fields = ('image',)

PhotoFormSet = forms.modelformset_factory(Photo, form=PhotoForm, extra=5,)

marketplace/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.views import generic

from .forms import MessageForm, PhotoFormSet, PostingForm
from .models import Posting, Photo

class IndexView(generic.ListView):
    template_name = "marketplace/index.html"
    context_object_name = "posting_list"

    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num_visits = self.request.session.get("num_visits", 0) + 1
        self.request.session["num_visits"] = num_visits
        context["num_visits"] = num_visits
        return context
    """

    def get_queryset(self):
        return Posting.objects.all()

class PostingCreateView(generic.edit.CreateView):
    model = Posting
    form_class = PostingForm

    def get_context_data(self, **kwargs):
        context = super(PostingCreateView, self).get_context_data(**kwargs)

        if self.request.POST:
            context['formset'] = PhotoFormSet(self.request.POST, self.request.FILES, queryset=Photo.objects.none())
            context['detail_form'] = PostingForm(self.request.POST)
        else:
            context['formset'] = PhotoFormSet(queryset=Photo.objects.none())
            context['detail_form'] = PostingForm()

        return context

    def post(self, request, *args, **kwargs):
        formset = PhotoFormSet(request.POST, request.FILES)
        detail_form = PostingForm(request.POST)
        if formset.is_valid() and detail_form.is_valid():
            return self.form_valid(formset, detail_form)

    def form_valid(self, formset, detail_form):
        self.object = detail_form.save(commit=False)

        if self.request.user.is_authenticated:
            self.object.user = self.request.user
            self.object.save()

            for photo_form in formset.cleaned_data:
                if photo_form:
                    image = photo_form['image']
                    photo = Photo(posting=self.object, image=image)
                    photo.save()

            return HttpResponseRedirect(self.get_success_url())
        else:
            raise Exception("no user logged in")

    def get_success_url(self):
        return reverse('marketplace:detail', kwargs={
            'pk': self.object.pk
        })

class PostingUpdateView(generic.edit.UpdateView):
    model = Posting
    form_class = PostingForm

    def get_context_data(self, **kwargs):
        context = super(PostingUpdateView, self).get_context_data(**kwargs)

        if self.request.POST:
            context['formset'] = PhotoFormSet(self.request.POST, self.request.FILES, queryset=Photo.objects.none())
            context['detail_form'] = PostingForm(self.request.POST)
        else:
            context['formset'] = PhotoFormSet(queryset=Photo.objects.none())
            context['detail_form'] = PostingForm()

        return context
    
    def get_success_url(self):
        return reverse('marketplace:detail', kwargs={
            'pk': self.object.pk
        })

class PostingDeleteView(generic.edit.DeleteView):
    model = Posting
    def get_success_url(self):
        return "/market/"

class DetailView(generic.DetailView):
    model = Posting
    template_name = "marketplace/detail.html"

def send_message(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)

    if request.method == 'GET':
        form = MessageForm()
    else:
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data['message']
            try:
                user_email = request.user.email
                subject = f"{user_email} is interested in your post on EasyLife!"
                send_mail(subject, message, from_email="admin@stevenseasylife.com", recipient_list=[posting.user.email])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('marketplace:send_message_confirm'))
    return render(request, 'marketplace/send_message.html', {'form': form, 'posting_id': posting_id})

def send_message_confirm(request):
    return render(request, 'marketplace/send_message_confirm.html')

marketplace/templates/marketplace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>StevensEasyLife</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'marketplace/style.css' %}">
  <style type="text/css">
    .errorlist{
      color: red;
    }
  </style>
</head>
<body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  <div class="container-fluid">
    <div class="col">
      <div>
      {% block navbar %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'landing:index' %}">EasyLife</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'marketplace:market_home' %}">Browse Marketplace</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'marketplace:make_post' %}">Make a Post</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item disabled">
                <a class="nav-link disabled">Hi, {{ user.get_username }}</a>
            </li>
            <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'django_registration_register' %}">Create an account</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'roommates:index' %}">Switch to Roommates</a>
            </li>
          </ul>
          <!--
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          -->
        </div>
      </nav>
     {% endblock %}
      </div>
      <div style="background-color: white" class="float-none">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

marketplace/templates/marketplace/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>StevensEasyLife</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'marketplace:market_home' %}">Home</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

marketplace/templates/marketplace/detail.html
{% extends "marketplace/base.html" %}

{% block content %}

<a href="{% url 'marketplace:market_home'%}" class="btn btn-primary btn-md float-md-left mr-1" role="button" aria-pressed="true">Back to Marketplace</a>
{% if posting.get_next_by_created %}
<a href="{% url 'marketplace:detail' posting.get_next_by_created.id %}" class="btn btn-primary btn-md float-md-left mr-1" role="button" aria-pressed="true">View Next</a>
{% endif %}
{% if user.id == posting.user.id %}
<a href="{% url 'marketplace:delete_post' posting.id %}" class="btn btn-primary btn-md float-md-right mr-1" role="button" aria-pressed="true">Remove Posting</a>
<a href="{% url 'marketplace:edit_post' posting.id %}" class="btn btn-primary btn-md float-md-right mr-1" role="button" aria-pressed="true">Edit Posting</a>
{% else %}
<a href="{% url 'marketplace:send_message' posting.id %}" class="btn btn-primary btn-md float-md-left mr-1" role="button" aria-pressed="true">Contact Poster!</a>
{% endif %}
<br>
<br>
<h1>{{ posting.title }}</h1>
<p>Price: ${{ posting.price }}</p>
<p>Description: {{ posting.description }}</p>

{% for photo in posting.photo_set.all %}
    <img src="{{photo.image.url}}" />
{% endfor %}
{% endblock %}

marketplace/templates/marketplace/index.html
{% extends "marketplace/base.html" %}
{% load static %}
{% block content %}
<h1 class="h3 mb-3 font-weight-normal">Marketplace Listings</h1>
{% if posting_list %}
    <div class="ml-5">
    {% for posting in posting_list %}
    <div class="row">
        <div class="border border-secondary mb-3 row col-md-8 container-fluid d-flex">
            <div class="col-md-2" style="flex: 0 0 100px">
                {% if posting.photo_set.all %}
                <img src="{{posting.photo_set.all.0.thumbnail.url}}" width="100" height="100" class="border"/>
                {% else %}
                <img src="{% static 'marketplace/images/no-photo.png' %}" width="100" height="100" class="border"/>
                {% endif %}
            </div>
            <div class="col-md">
                <h1 class="h5 mt-2 font-weight-normal"><a href="{% url 'marketplace:detail' posting.id %}">{{ posting.title}}</a></h1>
                <span>${{ posting.price }}</span>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    {% endfor %}
    </div>
{% else %}
    <p>No postings are available.</p>
{% endif %}
<br>
{% endblock %}

marketplace/templates/marketplace/posting_confirm_delete.html
{% extends "marketplace/base.html" %}

{% block content %}
<a href="{% url 'marketplace:detail' posting.id %}" class="btn btn-primary btn-md float-md-left" role="button" aria-pressed="true">Back to Posting</a>
<br>
<br>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete posting?</p>
    <button type="submit" class="btn btn-primary btn-md">Confirm</button>
</form>
{% endblock %}

marketplace/templates/marketplace/posting_form.html
{% extends "marketplace/base.html" %}

{% block content %}
{% if posting %}
<a href="{% url 'marketplace:detail' posting.id %}" class="btn btn-primary btn-md float-md-left" role="button" aria-pressed="true">Back to Posting</a>
{% else %}
<a href="{% url 'marketplace:market_home'%}" class="btn btn-primary btn-md float-md-left" role="button" aria-pressed="true">Back to Marketplace</a>
{% endif %}
<br>
<br>
{% if posting %}
<h1 class="h3 mb-3 font-weight-normal">Edit Posting</h1>
{% else %}
<h1 class="h3 mb-3 font-weight-normal">Make a Posting</h1>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="h5 mb-3 font-weight-normal">Enter Details</h1>
    {% for field in detail_form %}
      {{ field.label }}: <br>
      {{ field }} <br>
      <br>
    {% endfor %}
    <br>
    <h1 class="h5 mb-3 font-weight-normal">Upload Photos</h1>
    {{ formset.management_form }}
    {% for image_form in formset %}
      {{ image_form }} <br>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary btn-md">Post</button>
</form>
{% endblock %}

marketplace/templates/marketplace/send_message.html
{% extends "marketplace/base.html" %}

{% block content %}
  <a href="{% url 'marketplace:detail' posting_id %}" class="btn btn-primary btn-md float-md-left" role="button" aria-pressed="true">Back to Posting</a>
  <br>
  <br>
  <form method="post">
      {% csrf_token %}
      {% for field in form %}
      {{ field.label }}: <br>
      {{ field }} <br>
      <br>
    {% endfor %}
    <button type="submit" class="btn btn-primary btn-md">Send</button>
  </form>
{% endblock %}

marketplace/templates/marketplace/send_message_confirm.html
{% extends "marketplace/base.html" %}

{% block content %}
  <a href="{% url 'marketplace:market_home'%}" class="btn btn-primary btn-md float-md-left" role="button" aria-pressed="true">Back to Marketplace</a>
  <br>
  <br>
  <p>Your message has been sent!</p>
{% endblock %}